### ISSUE TITLE
Update docs for modulo

### ISSUE THREAD

**Issue by soegaard** [racket/zuo#19]
The docs for `modulo` need a note, that it return a remainder computed by the C operator `%`.
(Maybe rename to `remainder` - but I am not sure Racket `remainder` and C `%` compute the same.)

**Comment by mflatt** [comment]
Addressed by 25ad19ea481a62ab7f332a6db33b54bfb74eeeff, which renames `module` to `remainder`, but also adds `modulo` as a library function.
