### ISSUE TITLE
Please add copyright notices

### ISSUE THREAD

**Issue by weinholt** [racket/zuo#20]
Hello!

I'm working on the Debian packaging for Chez Scheme and plan to package Zuo since it is now a build dependency.

Could you please add copyright notices? I understand that the license is Apache-2.0 or MIT, but for the Debian packaging I need to write out copyright notices. It would really help to have the proper notices.

(It would also help if you tagged releases, but otherwise I will just use the commits that update `ZUO_VERSION` and `ZUO_MINOR_VERSION`).

/weinholt

**Comment by mflatt** [comment]
Hi @weinholt — Would it work for me to add

```
Copyright 2022-2023 Zuo Developers

Copyrights in the Zuo implementation are retained by their contributors.
No copyright assignment is required to contribute to Zuo.
```

at the start of "LICENSE.txt"? This approach is modeled in part on Rust's "COPYRIGHT.txt" and what I see in "/usr/share/doc/rustc/copyright" when I install Rust via `apt`.

I'm happy to start tagging versions.

**Comment by weinholt** [comment]
@mflatt Absolutely, that works for me. Thank you.

**Comment by mflatt** [comment]
Updated "LICENSE.txt" in 75381c30fbe9f71aebc53efe04b6778704b8285e.
For now, I've tag v1.9 (latest) and v1.8. Happy to add more version tags if they ever seem useful.
