### ISSUE TITLE
Embedding example does not work

### ISSUE THREAD

**Issue by markuspf** [racket/zuo#4]
If I just copy-and-paste the embedding-example from `zuo.h` into a C-file `five-app`, and compile using

```
gcc zuo.c five-app.c -DZUO_EMBEDDED -g -static -o five-app
```

then

```
# ./five-app
```

fails with

```
[five-appundefined: 'five-app
 in module->hash
```

after some time trying to understand the interpreter it turns out that it tries looking up `'five-app` in the environment (where it does not exist, why should it).

Anyway, using the following hack (?)

```
  ht = zuo_ext_eval_module(zuo_ext_string("five-app", strlen("five-app")), prog, strlen(prog));
```

makes it work, alternatively getting a quoted symbol works, too:

```
  ht = zuo_ext_eval_module(zuo_ext_cons(zuo_ext_symbol("quote"),
                                               zuo_ext_cons(zuo_ext_symbol("five-app"),
                                               zuo_ext_null())),
                                             prog, strlen(prog));
```

Can't claim to understand which one of these might be preferable, though.

In any case, thanks for this new toy ;)

**Comment by mflatt** [comment]
Thanks for the report! I think this quoting belongs in `zuo_eval_module` (which is used by `zuo_ext_eval_module`), so I'll add it there.
