### ISSUE TITLE
Does #lang zuo/base have a concept of return value?

### ISSUE THREAD

**Issue by doppioandante** [racket/zuo#6]
Hi, let's say I want to embed a zuo program that simply computes an expression:
`#lang zuo (+ 1 2)`
Giving this to `zuo_ext_eval_module` doesn't seem to produce a meaningful result; is there a way to retrieve the value of that expression?
I have also tried a workaround like: 
`#lang zuo (define (main) (+ 1 2))`
but I can't understand how to actually call the main function from the module.

Another option that I thought of of is forking, using (display) inside the embedded snippet and then reading the result as a string? I don't actually need the original data type maintained, but I'm wondering if I'm misunderstanding something fundamental.

**Comment by mflatt** [comment]
The `zuo` language will just print the result of any top-level form, and you're right that `zuo_ext_eval_module` just gives you the module's implementation with no simple way to extract a value or export from it.

I'll have to think about the right way for an embedding application to cooperate with `zuo`, as opposed to `zuo/kernel`. For now, here's an example that relies on the representation of provided variables in a `zuo` module.

```
#include <stdio.h>
#include <string.h>
#include "zuo.h"

/* Link with a copy of "zuo.c" created by `zuo local/image.zuo`. */

int main() {
  const char *prog = "#lang zuo (provide main) (define (main) (+ 1 2))";
  zuo_ext_t *ht, *prov_ht, *prov, *var, *main, *v;

  /* Step 1 */
  zuo_ext_primitive_init();

  /* Step 2 */
  zuo_ext_image_init(NULL);

  /* Step 3 */
  zuo_ext_runtime_init(zuo_ext_false(), zuo_ext_empty_hash());

  /* Run `prog`: */
  ht = zuo_ext_eval_module(zuo_ext_symbol("main-app"), prog, strlen(prog));

  /* This code depends on the encoding of `zuo` modules: */
  prov_ht = zuo_ext_hash_ref(ht, zuo_ext_symbol("macromod-provides"), zuo_ext_false());
  prov = zuo_ext_hash_ref(prov_ht, zuo_ext_symbol("main"), zuo_ext_false());
  var = zuo_ext_cdr(zuo_ext_car(zuo_ext_cdr(prov)));
  main = zuo_ext_apply(zuo_ext_hash_ref(zuo_ext_kernel_env(),
                                        zuo_ext_symbol("variable-ref"),
                                        zuo_ext_false()),
                       zuo_ext_cons(var, zuo_ext_null()));

  v = zuo_ext_apply(main, zuo_ext_null());
              
  printf("%s\n",
         zuo_ext_string_ptr(zuo_ext_apply(zuo_ext_hash_ref(zuo_ext_kernel_env(),
                                                           zuo_ext_symbol("~s"),
                                                           zuo_ext_false()),
                                          zuo_ext_cons(v, zuo_ext_null()))));

  return 0;
}
```

**Comment by mflatt** [comment]
I've added `'dynamic-require` mapped to `dynamic-require` in the module hash table, which provides a way to get values provided from modules in the `zuo/base` and `zuo` languages. The updated `zuo.h` provides a new example.

In trying this, I discovered that `zuo_ext_apply` didn't work right for calling non-primitives, so that's also fixed.

**Comment by doppioandante** [comment]
Thanks a lot, that's exactly what I needed.
